### ISSUE TITLE
[Feature Request] Translations for K40 Whisperer (I18N)

### ISSUE THREAD

**Issue by egrueda** [jkramarz/K40-Whisperer#7]
Would love to have K40 Whisperer in my own language, but I see all text strings are hardcoded in the code.
Is there any posibility for moving all those strings lo localized files, so we can use a custom language?
Of course, I can help with spanish translation :-D but I need the software to support this.

![image](https://user-images.githubusercontent.com/358397/71724320-332b3900-2e30-11ea-8e5d-524896e1d5ca.png)

**Comment by jkramarz** [comment]
Thank you @egrueda for your interest in making this software better. Unfortunately, this repository is very unofficial and is kept only as an archive of released versions. If you're interested in localized software for your K40, give a try to @tatarize's [meerk40t](https://github.com/meerk40t/meerk40t) - it is under active development and does accept contributions.

**Comment by egrueda** [comment]
Thank you very much for your recommendation

**Comment by tatarize** [comment]
The request to permit translations is already added in meerk40t/meerk40t#27. While this currently isn't done. There's a clear need for such translations, and a methodology in wx.Python for adding them. Though none of that is far enough along to provide helpful users with the ability to translate such things. You could email scorch and ask if he'd implement languages as such.
